name: Production Approval

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Jenkins build number"
        required: true
        type: string

jobs:
  production-approval:
    name: Production Approval
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Approval completed
        run: |
          echo "Production deployment approved."
          echo "Jenkins build: ${{ inputs.image_tag }}"